name: fast_event_bus
description: An event sending tool, convenient and fast, can be used across pages
version: 2.0.0
homepage: https://github.com/StrangerKjq/flutter_event_bus

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
